# Site settings
title: DATA 606 - Spring 2017
email: jason.bryer@gmail.com
description: > # this means to ignore newlines until "baseurl:"

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://data606.net" # the base hostname & protocol for your site
github_repo: "https://github.com/jbryer/DATA606Spring2017"
twitter_username: jbryer
github_username:  jbryer

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
job.title: ""
excerpt_separator: "<!--more-->"

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""
